Api.nvim_command 'set nu'
Api.nvim_command 'set linebreak'
Api.nvim_command 'set autoindent'
Api.nvim_command 'set ruler'
Api.nvim_command 'set showmode'
Api.nvim_command 'syntax on'
Api.nvim_command 'set ts=4'
Api.nvim_command 'set mouse=a'
Api.nvim_command 'set ignorecase'
Api.nvim_command 'let mapleader=" "'
