api.nvim_command 'set nu'
api.nvim_command 'set autoindent'
api.nvim_command 'set ruler'
api.nvim_command 'set showmode'
api.nvim_command 'syntax on'
api.nvim_command 'set ts=4'
api.nvim_command 'set mouse=a'
api.nvim_command 'let mapleader=" "'
